### PR TITLE
Link fix on random quote generator

### PR DESCRIPTION
**Pull request by Quantum-Codes**
https://leahcimto.github.io/python-random-quote/ was added instead of https://leahcimto.github.io/random_quote/ ig

### CODE REVIEW

**Comment by Quantum-Codes** [comment]
#25 link this... @leahcimto

**Review by PoIygon — APPROVED** [review]
Yeah I want this fixed too

**Comment by Quantum-Codes** [comment]
@leahcimto hello

**Comment by leahcimto** [comment]
This site no longer has anything on it. I may make it in the future, but for now I'm closing this.

**Pull request closed without merging**
