### PR TITLE
Fixed

### PR DESCRIPTION
**Pull request by CodeGuy92**
idk

### CODE REVIEW

**Comment by leahcimto** [comment]
looks good i dont see anything wrong with it thanks for making it

**Review by leahcimto — APPROVED** [review]

**Comment by leahcimto** [comment]
Also, just a tip since it looks like you are editing on the web version of github you can get github desktop and edit with the text editor of your choice

**Comment by CodeGuy92** [comment]
ur welcome also wait whats the difference between desktop and web

**Comment by leahcimto** [comment]
in the web version, you make a bunch of commits and the github web editor isn't really meant for making large changes on multiple files. with an editor like vscode you get a bunch of tools like auto fill, and you can preview your changes locally on your device.

**Comment by CodeGuy92** [comment]
ok

**Pull request merged**
