### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by MTM828**
Added a stats fetcher with 3D rotating loaders and improved your site's HTML and CSS code. (I also fixed the bug mentioned [here](https://github.com/leahcimto/leahcimto.github.io/issues/20).)
The stats fetchers sync your status and bio with your website and provide stats like followers, stars earned, etc.

Feel free to make any changes. :)

### CODE REVIEW

**Review by leahcimto — APPROVED** [review]

**Comment by MTM828** [comment]
Um... the status fetcher is responding with 403 (Forbidden), try replacing it with this code:
```javascript
"use strict";

var i;
const githubContent = document.querySelector("#test-dummy");
const userStatus = document.querySelector("#user-status");
const userBio = document.querySelector("#user-bio");
const userStats = document.querySelector("#user-stats");

// Needed so we don't bump into any CORS errors
$.ajaxPrefilter(function (options) {
    if (options.crossDomain && jQuery.support.cors) {
      var http = (window.location.protocol === 'http:' ? 'http:' : 'https:');
      options.url = http + '//cors-anywhere.herokuapp.com/' + options.url;
    }
});

// Fetch stats from https://api.github.com (will return followers, following, stars, etc.)
fetch("https://api.github.com/users/leahcimto")
    .then(response => response.json())
    .then(data => {
        userBio.innerHTML = data.bio;
        userStats.innerText =
          "Followers: "    + data.followers + " | " +
          "Following: "    + data.following + " | " +
          "Stars gained:"
        ;
    })
;
// Fetch the repos you have and their stats (used to count all the stars you've gained)
// (Note that gist stars aren't recorded.)
fetch("https://api.github.com/users/leahcimto/repos")
    .then(response => response.json())
    .then(data => {
        var starsGained = 0;
        for (i = 0; i < data.length; i++) {
            starsGained += data[i].stargazers_count;
        }
        userStats.innerHTML = "<b>" + userStats.innerText + " " + starsGained + "</b>";
    })
;
// Fetch ALL the content from https://github.com/leahcimto, and get the status from there since the github API doesn't provide your status :(
// This method is slow and requires like 3x loading time, but I think that it's the only way to do it.
$.get({
    crossOrigin: true,
    url: 'https://github.com/leahcimto',
    success: function (response) {
        githubContent.innerHTML = response;
        try {
            userStatus.innerHTML =
                githubContent.querySelector("div[data-team-hovercards-enabled]").innerText;
        } catch(err) {
            userStatus.innerHTML = null;
        }
        githubContent.innerHTML = null;
    }
});
// Also, the method of fetching is a bit different than the way all the other data is being fetched because github.com's CORS Policy is more strict than
// api.github.com's one.
```
I think I've/you've changed some code by accident.
If it still doesn't work then tell me so I can try another solution.

**Comment by leahcimto** [comment]
Done

**Comment by MTM828** [comment]
I don't think it's working...
I think that it's because the `cors-anywahere` website only provides temporary access to the database that lasts for 24 hours (probably for security reasons).
If that's the case, then we should probably forget it and find another site that gives unlimited access instead...

**Comment by MTM828** [comment]
I'll try fixing it (again).

**Comment by MTM828** [comment]
``` javascript
"use strict";

var i;
const githubContent = document.querySelector("#test-dummy");
const userStatus = document.querySelector("#user-status");
const userBio = document.querySelector("#user-bio");
const userStats = document.querySelector("#user-stats");

fetch("https://api.github.com/users/leahcimto")
    .then(response => response.json())
    .then(data => {
        userBio.innerHTML = data.bio;
        userStats.innerText =
          "Followers: "    + data.followers + " | " +
          "Following: "    + data.following + " | " +
          "Stars gained:"
        ;
    })
;
fetch("https://api.github.com/users/leahcimto/repos")
    .then(response => response.json())
    .then(data => {
        var starsGained = 0;
        for (i = 0; i < data.length; i++) {
            starsGained += data[i].stargazers_count;
        }
        userStats.innerHTML = "<b>" + userStats.innerText + " " + starsGained + "</b>";
    })
;
$.get({
    crossOrigin: true,
    url: 'https://cors.bridged.cc/github.com/leahcimto',
    success: function (response) {
        githubContent.innerHTML = response;
        try {
            userStatus.innerHTML =
                githubContent.querySelector("div[data-team-hovercards-enabled]").innerText;
        } catch(err) {
            userStatus.innerHTML = null;
            console.error(err);
        }
        githubContent.innerHTML = null;
    }
});
```
This should work. (Sorry for being so late LOL.)

**Pull request merged**
