### PR TITLE
Add a Top Navigation Bar

### PR DESCRIPTION
**Pull request by MTM828**
This is something that you see in every site, it'd be useful to have one.
Here's one I've made, you can edit it and use it (see index.html). No credit or license necessary!
And here are some notes:

- You have some slight indentation issues.
- Either add internal or (even better,) external CSS to speed up the process of coding the CSS.
- Plan the style of the site before creating it. I know that you're coding it right now, and not creating the site's style, keep up the good work!

And I changed that tiny dot into a guy. ┌(・。・)┘♪ LOL, why not? And I also changed his colour to #333333, he appears more hidden now too.
I hope this helps! 👍

### CODE REVIEW

**Comment by leahcimto** [comment]
Thanks! I'll review this soon.

**Review by leahcimto — APPROVED** [review]
Awesome! Looks good to merge

**Comment by MTM828** [comment]
Yay! Thanks. And happy to help!

**Comment by leahcimto** [comment]
I added credits on the README.md :P

**Comment by MTM828** [comment]
LOL, I said it doesn't matter. But thanks.

**Pull request merged**
